"""Security primitives used by the Secure QR Code Tool."""
from __future__ import annotations

import base64
import binascii
import os
from dataclasses import dataclass, field
from typing import Dict

from argon2.low_level import Type, hash_secret_raw
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from mnemonic import Mnemonic

from .config import AppConfig


class SecureString:
    """A mutable bytearray backed string that can be wiped from memory."""

    __slots__ = ("_data",)

    def __init__(self, data: bytes | str):
        if isinstance(data, bytes):
            self._data = bytearray(data)
        else:
            self._data = bytearray(data.encode("utf-8"))

    def get(self) -> str:
        """Return the string representation using UTF-8 decoding."""

        return self._data.decode("utf-8")

    def get_bytes(self) -> bytes:
        """Return a ``bytes`` view of the stored data."""

        return bytes(self._data)

    def copy(self) -> "SecureString":
        """Return a copy that owns its own backing buffer."""

        return SecureString(self.get_bytes())

    def clear(self) -> None:
        """Overwrite the backing buffer with zeros."""

        for index in range(len(self._data)):
            self._data[index] = 0
        self._data = bytearray()

    def __len__(self) -> int:  # pragma: no cover - trivial
        return len(self._data)

    def __enter__(self) -> "SecureString":  # pragma: no cover - trivial
        return self

    def __exit__(self, *_exc_info: object) -> None:  # pragma: no cover - trivial
        self.clear()

    def __del__(self):  # pragma: no cover - best effort cleanup
        try:
            self.clear()
        except Exception:
            pass


@dataclass(slots=True)
class CryptoManager:
    """High level facade around encryption primitives."""

    config: AppConfig

    def _derive_key(self, password: SecureString, salt: bytes) -> bytes:
        """Derive an AES key from ``password`` using the configured KDF."""

        if self.config.kdf.lower() == "argon2id":
            return hash_secret_raw(
                secret=password.get_bytes(),
                salt=salt,
                time_cost=self.config.argon2_time_cost,
                memory_cost=self.config.argon2_memory_cost_kib,
                parallelism=self.config.argon2_parallelism,
                hash_len=self.config.aes_key_size_bytes,
                type=Type.ID,
            )

        if self.config.kdf.lower() == "pbkdf2":
            kdf = PBKDF2HMAC(
                algorithm=hashes.SHA256(),
                length=self.config.aes_key_size_bytes,
                salt=salt,
                iterations=self.config.pbkdf2_iterations,
                backend=default_backend(),
            )
            return kdf.derive(password.get_bytes())

        raise ValueError(f"Unsupported KDF: {self.config.kdf}")

    def _build_aad(self) -> bytes:
        """Return the associated data bound into the AEAD payload."""

        aad_parts = (
            self.config.app_name,
            self.config.app_version,
            self.config.kdf.lower(),
            "aes-256-gcm",
        )
        return "|".join(aad_parts).encode("utf-8")

    def encrypt(self, data: SecureString, password: SecureString) -> Dict[str, str]:
        """Encrypt ``data`` using AES-256-GCM.

        The method returns a JSON serialisable dictionary containing the salt,
        nonce and ciphertext encoded in base64.
        """

        salt = os.urandom(self.config.salt_size_bytes)
        key = self._derive_key(password, salt)
        aesgcm = AESGCM(key)
        nonce = os.urandom(12)
        ciphertext = aesgcm.encrypt(nonce, data.get_bytes(), self._build_aad())

        return {
            "salt": base64.b64encode(salt).decode("ascii"),
            "nonce": base64.b64encode(nonce).decode("ascii"),
            "ciphertext": base64.b64encode(ciphertext).decode("ascii"),
            "version": self.config.app_version,
        }

    def decrypt(self, payload: Dict[str, str], password: SecureString) -> SecureString:
        """Decrypt the dictionary generated by :meth:`encrypt`."""

        required = {"salt", "nonce", "ciphertext"}
        missing = required.difference(payload)
        if missing:
            raise ValueError(f"Invalid payload, missing fields: {sorted(missing)}")

        try:
            salt = base64.b64decode(payload["salt"], validate=True)
            nonce = base64.b64decode(payload["nonce"], validate=True)
            ciphertext = base64.b64decode(payload["ciphertext"], validate=True)
        except (TypeError, binascii.Error) as exc:
            raise ValueError("Payload contains invalid base64 data") from exc

        if len(salt) < self.config.salt_size_bytes:
            raise ValueError("Payload contains an invalid salt length")

        key = self._derive_key(password, salt)
        aesgcm = AESGCM(key)

        try:
            plaintext = aesgcm.decrypt(nonce, ciphertext, self._build_aad())
        except Exception as exc:  # pragma: no cover - depends on ciphertext
            raise ValueError("Decryption failed") from exc

        return SecureString(plaintext)


@dataclass(slots=True)
class MnemonicManager:
    """Utility wrapper around the ``mnemonic`` package."""

    _WORD_COUNT_TO_STRENGTH = {12: 128, 18: 192, 24: 256}

    config: AppConfig
    _mnemonic: Mnemonic = field(init=False, repr=False)
    _default_word_count: int = field(init=False, repr=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, "_mnemonic", Mnemonic("english"))
        default = getattr(self.config, "mnemonic_default_words", 24)
        if default not in self._WORD_COUNT_TO_STRENGTH:
            raise ValueError(
                "mnemonic_default_words must be one of: "
                f"{sorted(self._WORD_COUNT_TO_STRENGTH)}"
            )
        object.__setattr__(self, "_default_word_count", default)

    @property
    def default_word_count(self) -> int:
        return self._default_word_count

    @classmethod
    def valid_word_counts(cls) -> tuple[int, ...]:
        return tuple(sorted(cls._WORD_COUNT_TO_STRENGTH))

    def generate(self, word_count: int | None = None) -> str:
        if word_count is None:
            word_count = self._default_word_count
        try:
            strength = self._WORD_COUNT_TO_STRENGTH[word_count]
        except KeyError as exc:  # pragma: no cover - defensive
            raise ValueError(
                "word_count must be one of: "
                f"{sorted(self._WORD_COUNT_TO_STRENGTH)}"
            ) from exc
        return self._mnemonic.generate(strength=strength)

    def validate(self, mnemonic: str) -> bool:
        return self._mnemonic.check(mnemonic)

    @staticmethod
    def checksum(mnemonic: str) -> str:
        import hashlib

        return hashlib.sha256(mnemonic.encode("utf-8")).hexdigest()[:6].upper()


__all__ = ["SecureString", "CryptoManager", "MnemonicManager"]
